<a href="https://colab.research.google.com/github/bhakti0720/ML_learnings/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this note book i'm going to show you how to do one-hot encoding by using Pandas and the Sklearn libraries<br>

For this i'm using the cars.csv dataset.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("cars.csv")

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

# Understanding the data

Here we have 3 categorical columns

let's see it one by ine

In [21]:
df['brand'].unique()
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [22]:
df['brand'].nunique()

32

In [16]:
df['fuel'].unique()
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [23]:
df['fuel'].nunique()

4

In [15]:
df['owner'].unique()
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [24]:
df['owner'].nunique()

5

## OneHotEncoding using Pandas
So in ur dataset, the brand column has 32 unique values.

That's a huge value 😶
  
which can increase dimensionality if we directly apply encoding.

This can lead to:
- High memory usage  
- Increased model complexity  
- Risk of overfitting  

👽Solution: Threshold-based Grouping

To reduce dimensionality, we apply a **threshold**.

We keep only those brands that appear **more than 100 times**  
All other less frequent brands are grouped into a single category: **"Uncommon"**

In [29]:
counts = df['brand'].value_counts()
print(counts)

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [28]:
df['brand'].nunique()
threshold = 100

In [31]:
repl = counts[counts <= threshold].index
print(repl)

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

This repl variable stores all the uncommon cars brand

It will stores all this brands in array

Now we are using the Pandas get_dummies class to encode the brand column

In [33]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5639,0,0,0,0,0,0,1,0,0,0,0,0,0
6222,0,0,0,0,0,0,1,0,0,0,0,0,0
7411,0,0,0,0,0,0,0,0,0,0,1,0,0
7891,0,0,0,0,0,0,0,0,0,0,1,0,0
1563,0,0,0,0,0,0,0,0,0,0,0,0,1

Doing the one-hot encoding for the
- fule
- owner

In [35]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## K-1 One-Hot Encoding for 'fuel' and 'owner'

### What is K-1 One-Hot Encoding?

In One-Hot Encoding, if a column has **K categories**, we create **K-1 dummy variables** instead of K.


### Why do we use K-1 encoding?

To avoid **Dummy Variable Trap (Multicollinearity)**.

When we create K dummy variables:
- One column can be predicted using others  
- This creates **redundant information**  <br>
(Note the above point)

Example:
If we create 4 dummy variables:
- Diesel  
- Petrol  
- CNG  
- LPG  

One column becomes redundant because:
If we know 3 values, we can automatically determine the 4th.
so we drop 1 column from it (i.e the k-1)


###  What is the Dummy Variable Trap? 🪤

It is a situation where:
- One feature is **perfectly dependent** on others (idealy i/p columns should be independent of each other )
- This causes problems in models like **Linear Regression**  


###  How K-1 solves this?

 By dropping one category:
- We remove redundancy  
- Model becomes stable and efficient

In [37]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True, dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

## OneHotEncoding using Sklearn

Generally we ues encoding by using Sklearn in Ml

you might think why ???<br>
bcz
- sklearn encoders (like `OneHotEncoder`) learn categories during training (`fit`)
- Apply the same transformation on test data (`transform`)

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [39]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [41]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])
X_train_new.shape

(6502, 7)

Here we are getting the final 7 columns as a result <br>
bcz:
- 3 columns from the fules (after removing 1 from the total of 4)
- 4 columns from the owner (after removing 1 from the total of 5)

## Joining the data frame by using the hstack class from numpy

In [43]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new.toarray()))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)